$('.owl-carousel').owlCarousel({
  loop:true,
  margin:50,
  center: true,
  autoWidth:true,
  autoplay:true,
  autoplayTimeout:2000,
  autoplayHoverPause:true,
  responsiveClass:true,
  responsive:{
      0:{
          items:1,
          nav:false
      },
      600:{
          items:2,
          nav:false
      },
      1000:{
          items:4,
          nav:false,
          loop:true
      }
  }
})
